server:
  port: 9090

spring:
  security:
    user:
      name: kolayik
      password: 1234
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kolayikdb
    username: postgres
    password: 196969
  jpa:
    hibernate:
      ddl-auto: create
  mail:
        host: smtp.gmail.com
        port: 587
        username: berkans.akbuluts@gmail.com
        password: wlkschnzisueaaeb
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
  jackson:
    time-zone: Europe/Istanbul